//  Copyright DataWiseHQ/grule-rule-engine Authors
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

package unique

import (
	"math/rand/v2"
	"strconv"
)

// NewID will create a new unique ID string. With 128 bits of uniqueness
// per generated ID, IDs generated by this function have 6 more bits of
// randomness than UUIDv4, generally ensuring that no two identical IDs
// will ever be generated.
func NewID() string {
	// As of go 1.22, the default rand source is ChaCha8: https://go.dev/blog/chacha8rand.
	upper := strconv.FormatUint(rand.Uint64(), 36)
	lower := strconv.FormatUint(rand.Uint64(), 36)
	return upper + "-" + lower
}
